// Simplified sea distance database (Muğla çıkışlı, deniz mili)
const SEA_DISTANCES = {
  "Yunanistan - Rodos": 60,
  "Kıbrıs - Mağusa (Famagusta)": 387,
  "İtalya - Bari": 632,
  "Mısır - İskenderiye (Alexandria)": 427,
  "Lübnan - Beyrut": 503,
  "Suriye - Lazkiye (Latakia)": 476,
  "İsrail - Hayfa (Haifa)": 518,
  "Libya - Trablus": 854,
  "Tunus - Tunis/La Goulette": 944,
  "Cezayir - Cezayir (Algiers)": 1342,
  "Fas - Tanca (Tangier)": 1840,
  "Malta - Valletta": 721,
  "Fransa (Med.) - Marsilya": 1237,
  "İspanya (Med.) - Barselona": 1379,
  "Slovenya - Koper": 920,
  "Hırvatistan - Split": 730,
  "Karadağ - Bar": 564,
  "Arnavutluk - Dıraç (Durrës)": 519,
  "Bosna-Hersek - Neum": 658,
  "Sudan - Port Sudan": 1340,
  "Cibuti - Cibuti": 2009,
  "Suudi Arabistan - Cidde (Jeddah)": 1284,
  "Umman - Muscat": 2054,
  "Hindistan - Mumbai (Nhava Sheva)": 3001,
  "Pakistan - Karaçi (Karachi)": 2469,
  "Sri Lanka - Colombo": 3881,
  "Çin - Şanghay (Shanghai)": 5157,
  "Endonezya - Cakarta (Jakarta)": 5895,
  "Kenya - Mombasa": 2944,
  "Tanzanya - Darüsselam": 3120,
  "Güney Afrika - Cape Town": 4933,
  "ABD (Atlantik) - New York/Newark": 5123,
  "Kanada (Atlantik) - Halifax": 4528,
  "Brezilya - Santos": 6374,
  "Arjantin - Buenos Aires": 7395,
  "Meksika (Atlantik) - Veracruz": 7087,
  "Avustralya - Sydney": 9305,
  "Yeni Zelanda - Auckland": 10635
};

window.SEA_DISTANCES = SEA_DISTANCES;